export const CREATE_POST = "CREATE_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";

export const LOAD_POSTS = "LOAD_POSTS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";

export const LOAD_SINGLE_POST = "LOAD_SINGLE_POST";
export const LOAD_SINGLE_POST_SUCCESS = "LOAD_SINGLE_POST_SUCCESS";
export const LOAD_SINGLE_POST_ERROR = "LOAD_SINGLE_POST_ERROR";

export const SET_GAUTH = "SET_GAUTH";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
